# Generated by Django 2.0 on 2020-04-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judapp', '0001_initial'),
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('num_office', models.CharField(max_length=3, verbose_name='Номер кабинета')),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapp.JobTitle', verbose_name='Должность')),
                ('jud_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judapp.JudSite', verbose_name='Наименование СУ')),
            ],
            options={
                'ordering': ('jud_site', 'last_name', 'first_name'),
                'select_on_save': True,
            },
        ),
    ]
