# Generated by Django 2.0 on 2020-06-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('mobN', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('passwd', models.CharField(max_length=128)),
                ('agent', models.CharField(max_length=10, verbose_name='Название компании')),
                ('contract', models.CharField(default=True, max_length=10, verbose_name='Номер договора с агентом')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('type_account', models.CharField(max_length=50, verbose_name='Тип')),
                ('tag', models.CharField(max_length=50, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_name', models.CharField(max_length=50, verbose_name='Название валюты')),
                ('curr_num_code', models.PositiveSmallIntegerField(verbose_name='Код валюты')),
                ('curr_char_code', models.CharField(max_length=3, verbose_name='Знак валюты')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, verbose_name='Название региона (страны)')),
                ('region_code', models.CharField(max_length=3, verbose_name='Код региона (страны)')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust', models.IntegerField(null=True, verbose_name='Размер кредита доверия')),
                ('limittransaction', models.IntegerField(null=True, verbose_name='Размер лимита списания денежных средств')),
                ('limitperday', models.IntegerField(null=True, verbose_name='Лимит списания денег за сутки')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modify_at', models.DateTimeField(auto_now_add=True)),
                ('modify_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='trans_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.TransactionsDetail'),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='uuid_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Regions', verbose_name='Страна'),
        ),
    ]
