# Generated by Django 2.0 on 2020-04-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Monitor', verbose_name='Монитор')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Printer', verbose_name='Принтер')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Scanner', verbose_name='Сканер')),
                ('sysblock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.SysBlock', verbose_name='Системный блок')),
                ('ups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Ups', verbose_name='ИБП')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.WorkUser', verbose_name='Сотрудник')),
            ],
            options={
                'ordering': ('worker',),
                'select_on_save': True,
            },
        ),
    ]
