# Generated by Django 3.0.3 on 2020-02-17 11:18

from django.db import migrations


def forwards_func(apps, schema_editor):
    judsite_model = apps.get_model("judapp", "JudSite")
    jobtitle_model = apps.get_model("jobapp", "JobTitle")
    judsite_obj = judsite_model.objects.create(
        pk=1,
        jud_site="Судебный участок №44 г.Амурска и Амурского района",
        jud_site_short="СУ 44 г.Амурск"
    )
    judsite_obj = judsite_model.objects.create(
        pk=2,
        jud_site="Судебный участок №45 г.Амурска и Амурского района",
        jud_site_short="СУ 45 г.Амурск"
    )
    judsite_obj = judsite_model.objects.create(
        pk=3,
        jud_site="Судебный участок №46 п.Эльбан и Амурского района",
        jud_site_short="СУ 46 п.Эльбан"
    )
    judsite_obj = judsite_model.objects.create(
        pk=4,
        jud_site="Судебный участок №74 г.Амурска и Амурского района",
        jud_site_short="СУ 74 г.Амурск"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=1,
        job_title="Мировой судья",
        job_title_short="Мировой судья"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=2,
        job_title="Помощник мирового судьи",
        job_title_short="Помощник МС"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=3,
        job_title="Секретарь судебного участка",
        job_title_short="Секретарь СУ"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=4,
        job_title="Секретарь судебного заседания",
        job_title_short="Секретарь СЗ"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=5,
        job_title="Инспектор",
        job_title_short="Инспектор"
    )
    jobtitle_obj = jobtitle_model.objects.create(
        pk=6,
        job_title="Ведущий эксперт",
        job_title_short="Ведущий эксперт"
    )


def reverse_func(apps, schema_editor):
    judsite_model = apps.get_model("judapp", "JudSite")
    jobtitle_model = apps.get_model("jobapp", "JobTitle")

    # Delete all objects
    judsite_model.objects.all().delete()
    jobtitle_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
