# Generated by Django 2.0 on 2020-04-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fill_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Printer', verbose_name='Принтер'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Scanner', verbose_name='Сканер'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='ups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemsapp.Ups', verbose_name='ИБП'),
        ),
    ]
