# Generated by Django 2.0 on 2020-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=40, verbose_name='Полное наименование должности')),
                ('job_title_short', models.CharField(max_length=15, verbose_name='Сокращенное наименование должности')),
            ],
            options={
                'ordering': ('job_title_short',),
                'select_on_save': True,
            },
        ),
    ]
